name: Dealii

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
  schedule:
    - cron: '5 2 * * 0'

jobs:

  dealii-build:

    runs-on: ubuntu-latest
    strategy:
        matrix:
            directory:
              - ubuntu-package-18
              - ubuntu-package
              - master-bare-gcc
              - master-bare-clang
              - for-dealfem
              - for-dealfem-latest-gcc
              - for-dealfem-latest-clang

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build ${{ matrix.directory }} --tag "rrastak/dealii:${{ matrix.directory }}"

      - name: Log into registry
        if: success()
        run: echo "${{ secrets.docker_pass }}" | docker login -u rrastak --password-stdin

      - name: Push image
        run: docker push "rrastak/dealii:${{ matrix.directory }}"
